### ISSUE TITLE
Reboot when scanning

### ISSUE THREAD

**Issue by aoki68k-lj** [CANDY-HOUSE/SesameSDK_ESP32_with_DemoApp#5]
In the sample program, when scanning advertisement packets, processing is performed on the assumption that manufacturer specific data exists.
https://github.com/CANDY-HOUSE/SesameSDK_ESP32_with_DemoApp/blob/b4dd05fa2e393748ab7c85c3c250b036b1d896a6/main/blecent.c#L119
If the advertisement packet does not contain manufacturer specific data, the program will run out of control because it will access an invalid pointer.
(Problems occur when there are multiple various BLE devices in the vicinity.)

**Comment by js4jiang5** [comment]
> In the sample program, when scanning advertisement packets, processing is performed on the assumption that manufacturer specific data exists.

Hi, I followed the document and successfully build and flash ESP32C3, but it seems that the ESP32C3 didn't find the Sesame lock because it's not locked when I unlocked it. What step did I miss? Should the lock need reset to factory mode to make it unregistered? I'll appreciate if you can give me some help.
TIA

**Comment by MotoZe** [comment]
Hi there,

Thank you for reaching out and providing details on the issue you're encountering. Let's address it step by step:

First, please ensure that your Sesame5 lock is in an unregistered state and positioned in the unlocked position. This is crucial for the initial setup.

Upon starting, the ESP32 program is designed to automatically detect and register any nearby Sesame5 locks and proceed to lock them as part of its initial setup routine.

Please verify these conditions and try again. If you continue to face difficulties, don't hesitate to reach back. We're here to help!

Best regards,

Motozawa

**Comment by js4jiang5** [comment]
> Please verify these conditions and try again. If you continue to face difficulties, don't hesitate to reach back. We're here to help!
> 
> Best regards,
> 
> Motozawa

@MotoZe 
Hi, I've successfully run the demo and found the unregistered Sesame5 Lock and registered it. I've also integrated the Sesame5 Lock to the Home Assistant with no problem. However, when I tried to do the same for Sesame Touch, although it can be successfully registered, but reconnection failed after reboot. The error message is "blecent.c: disconnect; reason=531". According to reason 531, the disconnection is caused by Sesame Touch. Do you know how to fix it? Is the ssm_chr_uuid and ssm_ntf_uuid different for Sesame5 Lock and Sesame Touch? Please help! 

Best Regards,
JS

**Comment by js4jiang5** [comment]
Never mind. I've figured it out and integrated both Sesame5 and Touch into Home Assistant.  Adding fingerprints and cards into Sesame Touch is also accomplished through Home Assistant.

**Comment by MotoZe** [comment]
Thank you for the update! I'm thrilled to hear that you've successfully integrated both Sesame5 and Touch into Home Assistant and managed the addition of fingerprints and cards seamlessly. Your ability to troubleshoot and fine-tune the integration is quite impressive. Should you need any more assistance or have further questions down the line, don't hesitate to reach out. Great job!
